### ISSUE TITLE
Problems ArrayAdapter - ListView   don't work  

### ISSUE THREAD

**Issue by erickTornero** [erickTornero/Android-BlueTooth-Robi#1]
I created an ArrayAdapter object to set the ListView items, but the instruction "add" doesn't work.

`listDevicesBT = (ListView) findViewById(R.id.ListBtDevices);`
```java
arrayAdapter = new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,lista);
listDevicesBT.setAdapter(arrayAdapter);

     
public void exampleFunction(View v)
{
    arrayAdapter.add("hello");
} 
```
When I run this App in my Mobile, this instruction break the app

**Comment by JosephPG** [comment]
change this `ArrayAdapter <String> arrayAdapter` for `ArrayAdapter arrayAdapter` in your variable  declaration

**Comment by erickTornero** [comment]
This is solved, I deleted the third term of parameters when I create an array adapter, It was unecessary
```java
listDevicesBT = (ListView) findViewById(R.id.ListBtDevices);

arrayAdapter = new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1);
listDevicesBT.setAdapter(arrayAdapter);

     
public void exampleFunction(View v)
{
    arrayAdapter.add("hello");
} 
```
